package ru.netology

data class Post(
    var id: Int = 0,
    val ownerId: Int,
    val fromId: Int,
    val createdBy: Int,
    val date: Int,
    val text: String,
    val replyOwnerId: Int = 0,
    val replyPostId: Int = 0,
    val friendsOnly: Boolean = false,
    val comments: List<Comment>?,
    val copyright: String,
    val likes: Int?,
    val repost: Post?,
    val views: Int?,
    val postType: String,
    val attachments: Attachment?,
    val signerId: Int = 0,
    val copyHistory: String,
    val canPin: Boolean,
    val canDelete: Boolean,
    val canEdit: Boolean,
    val isPinned: Boolean,
    val markedAsAds: Boolean,
    val isFavorite: Boolean,
    val donut: Donut?,
    val postponedId: Int = 0,
)